language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: ABid1IRAOV/KWuikiedebljNCbUoLiFmr+x7+VSc4lpRr8jpQd6uBT4pki/5/StFdJ47GIysUUAeFkfCSAtue9Xaiwr5AHRiTRLLseDmb26T8s5WaNfnefklqs1USn8W96naA2m3PWIxrc8JlrUwQRgQX0ZLVNeXqLvHwhpb36TkDp0X6/BQk6kPqY4ql6IgcjzCRMpNsC3NDic9CPaU+xHphWzZ8Sw1e1lWHrpJG5/rtwDgwH7Q+nJmXuT/1GbO/w7CdPo4YJ6YA9Bnagmlx9PJIt+ezTdJryEm/wri7PKZKoh8m0aqnSNUuiLVtjTT8DCz4p0zNDWfNIMjn975p6eDynmssr53hp+Ddq2j/eyvY1kjh28KVd0wSqiaG22ttjp3L2rff5Cmeq1QZ8aK3fm+iNyuopposeKKCcBlasT/5g7qkCEsrv2B1/cpW4cNt97dAe+7l26yv5OpFNVoNa4HACahVRntyE3Oxtkm7Z8/FlqvwfxiayCI0lidwKMH/7RMZInAy3P2VQAxvxt1BOQvTMc7+K2T4xRCfWDFQx4+mWLK3hiLhL+RIeHTaJy54BrERF8EZax1lUMWN0XPP1u0UkAlLNUmXHADoYsRt93YUsAPZz8BYUC85kIqGgu08xcHFuMhJklZDgen/J6CFQQoX7JyE30gsU2K66BE72E=
  on:
    repo: kuzzleio/kuzzle-plugin-logger
    branch: master
