language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: rjYvqg63O/g+QMp8FPJ9b6NtACY5fW6fYuP8105ZvZxXjMHCF3H3CpPp4+srwpij0GfTHfeagnmtwo/5AyEOlejkkIQAwKNrb+x2Lou5dCcqzSQYLHUWkrKC1iuwyqIh1gjvT+5i/Lv6n56u9cbDfjWkPMHmeatZ3rLIJianDAFgrwVnZvAe521MW7pOXwvb2rgaR7TstKPkrOxKlUWLnfp/nXv8H6Y2Qu28Yg5X5LqoCIWN266xpvzy++lhYU6hrUYFg87FarkaGq9n1cMstEcjDXw+TNTSGgP2ax9UD8yNMBuyyofnYTBoNWoEVwyAtC44kC25J9HroERAKxKMOUzor9fx5sBDhTk2FiKNJLLLSwU93uo3g++e9ydhgK65TKMHk8ULNjsT+BRNtsyyxBonUjqWylBDXCcSJTC6nut6vKz1F/3t+Drys1TvHPzgx+RAa+ERljmgPVsOF8ZpkDEemLGXVJo1y6Pr0vnTuSt8bU9WjJM7KVM7KwEmbKuxrIL5D4hQ0BG28e7/FAcLOzP/yjAi4/xO3e9mR6J26MYHAXzW2Cv3gA9IHH3/Cvdtxbc47jJdQMaiFgPh1P3IvSjmMmMfd9h9h0p2c4UzOi/R5L/SKQK/xi8OkY+PgOPQEJUwuHbSOIXNTWWudw8Ti2N7cFF+GUL1qwEUjCUB/wE=
  on:
    repo: kuzzleio/kuzzle-plugin-logger
    branch: master
