language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: lXJZQYPy7Q06IcSgdM36HicksBJ9j+xInkKPIl9SJlCWaXj8xe5Exhxb6bcXgrmU2d2+Uo10/jNAkYX8rjyUpcoQ1ZN+6cl+L+M3mYC/66nvmoOg9KeqLQ4rqA5kNDPe4oFZpFzpREy4SkK1OaktN8a8N3x0FQprxbXk8BPIiaWUoXs5WDTbIwVhM2nmLHvt+MvWjnuegr4VENbgTQRwVrH0pM1KggsJMEj9TneIeHoYdv7fadweQ2j23kq/w6NpVGIbKPp0yFrEuwBvQaylh/Qh5nowji1Jl4GEwBvd+xIgVGk9FJQ5PNbfqWgomHjppjm4gFhSOGnghNdIyfZwcwcXrhOf2b3Qdm+cILTbQx/I/Mm309EltDprExK+BUfM6dRhriIw34GVCD0FhIzV2F8z02u3LhOU7EmuwimDc3Wk6vuzK4rEf9EliE503F1d89BNAsZv9Is7f2/TIRFlisNeiqLvZ0T1x6EodIiKXHDH3sv6LhueLIXOaa0+6Wfbkxg+DVPDlRo2bYpj0cPuBuycvvafQT3zv0P7hTZC2++Cfwqdq9iE0F19d4Ts6Lzut+EkRoG1QniK4NY1z7ampjFBz/bHsRZMpsDRZATpGrgB/T+BL7efQnyewsYJ+TRumNJNTipmLBevTcelgbxxu2S/sx4kmojD2nHViXslu0Q=
  on:
    repo: kuzzleio/kuzzle-plugin-logger
    branch: master
