language: node_js
node_js:
  - 0.12.0

before_script:
  - npm install -g grunt

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false