module.exports = {
  'log:silly': 'silly',
  'log:verbose': 'verbose',
  'log:info': 'info',
  'log:debug': 'debug',
  'log:warn': 'warn',
  'log:error': 'error',
  'data:*': 'silly',
  'subscription:*': 'silly',
  'websocket:*': 'silly',
  'prepare:*': 'info',
  'cleanDb:done': 'info',
  'cleanDb:error': 'error',
  'server:*': 'info',
  'rabbit:started': 'info',
  'rabbit:error': 'error',
  'rabbit:stopped': 'info',
  'internalBroker:*': 'info',
  'room:new': 'debug',
  'room:remove': 'debug',
  'workerGroup:loaded': 'info',
  'profiling:*': 'info'
};