module.exports = {
  'log:silly': 'silly',
  'log:verbose': 'verbose',
  'log:info': 'info',
  'log:debug': 'debug',
  'log:warn': 'warn',
  'log:error': 'error',
  'data:*': 'silly',
  'security:*': 'silly',
  'protocol:*': 'silly',
  'subscription:*': 'silly',
  'websocket:*': 'silly',
  'prepareDb:*': 'info',
  'cleanDb:done': 'info',
  'cleanDb:error': 'error',
  'server:*': 'silly',
  'internalBroker:*': 'info',
  'room:new': 'debug',
  'room:remove': 'debug',
  'workerGroup:loaded': 'info',
  'profiling:*': 'info'
};
